spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gis-feature-group
      auto-offset-reset: latest  # 核心：启动只消费新消息，跳过所有历史旧任务
      # 增加会话超时时间（默认 10s）
#      properties:
#        session.timeout.ms: 30000
#        # 增加最大轮询间隔（默认 5min）
#        max.poll.interval.ms: 600000
#        # 心跳间隔（应为 session.timeout.ms 的 1/3）
#        heartbeat.interval.ms: 10000

gdal:
  library:
    path: gdalalljni